apiVersion: v1
kind: ConfigMap
metadata:
  name: medusa-config
  namespace: medusa
  labels:
    app.kubernetes.io/name: medusa
    app.kubernetes.io/component: app
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  REDIS_URL: "redis://medusa-redis:6379"
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in"
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up"
  NEXT_PUBLIC_APPWRITE_MAX_UPLOAD_SIZE: "52428800"
