apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medusa-redis-data
  namespace: medusa
  labels:
    app.kubernetes.io/name: medusa
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
